---
title: "4 cities"
author: "judy teng"
date: "July 30, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#sf 
#this chunk creates sf_df, a dataframe with obs from SF

sf_df <- read.xls("SFdf")
  sf_df <- sf_df %>%
    mutate(e= c(1:1782))
  
#sf_prices <- read_csv("SFprices")         sf prices and ids not needed; already in sf_df
#sf_prices <- sf_prices[-c(1:18),]
 # sf_prices <- sf_prices %>%
  #  mutate(e = c(1:1782))
  
#sf_ids <- read_csv("SFids")
 # sf_ids <- sf_ids %>%
  #  mutate(e = c(1:1782))

sf_final <- sf_df %>%
  mutate(city = "sf")

```



```{r}
# new york city
#this chunk creates a ny_df, a dataframe with obs from NYC

ny_df <- read.xls("NYdf") %>%
  ny_df <- ny_df %>%
  mutate(e= c(1:1800))

#ny_prices <- read_csv("NYprices")        ny price & id not needed; alreading in ny_df
  #ny_prices <- ny_prices %>%
  #mutate(e= c(1:1800))

#ny_ids <- read_csv("NYids") 
  #ny_ids <- ny_ids  %>%
  #mutate(e = c(1:1800))
ny_final <- ny_df %>%
  mutate(city = "nyc")
```


```{r}
#los angeles 
#this chunk creates la_df, a dataframe with obs from LA
la_df <- read.xls("LAdf")
  la_df <- la_df %>%
    mutate(e = c(1:1800))
  
#la_prices <- read_csv("LAprices")      la price and ids not needed; already in la_df
 # la_prices <- la_prices %>%
  #  mutate(e = c(1:1800))
  
#la_ids <- read_csv("LAids")
 # la_ids <- la_ids %>%
  #  mutate(e = c(1:1800))
  
la_final <- la_df %>%
  mutate(city = "la")
```


```{r}
#chicago
#this chunk creates ch_df, a dataframe with obs from Chicago

ch_df <- read.xls("Chicagodf.xls")
  ch_df <- ch_df %>%
    mutate(e= c(1:1799))
  
#ch_prices <- read.csv("Chicagoprices")       chicago id and price not needed, already in ch_df
#ch_prices <- ch_prices[-1,] %>%
 # as.data.frame() %>%
  #  mutate(e = c(1:1799))
#colnames(ch_prices) <- c("pricelistings","e")

#ch_ids <- read.csv("Chicagids")       
#ch_ids <- ch_ids[-1,] %>%
 # as.data.frame() %>%
  #  mutate(e = c(1:1799))

ch_final <- ch_df %>%
  full_join(ch_prices) %>%
  mutate(city = "ch")
```


```{r}
#this chunk creates the 5 csv's with 17 common observations among the 4 cities
# csv outputs: cleaned_sf.csv, cleaned_la.csv, cleaned_ch.csv, cleaned_ny.csn, four_cities.csv

sf_cols <- names(sf_final)
la_cols <- names(la_final)
ny_cols <- names(ny_final)
ch_cols <- names(ch_final)

# this code finds mutual columns between the four data frames: sf_final, la_final, ch_final, ny_final
sf_common_cols <- sf_cols[sf_cols %in% la_cols]
ny_common_cols <- ny_cols[ny_cols %in% la_cols]
ch_common_cols <- ch_cols[ch_cols %in% la_cols]
la_common_cols <- la_cols

sf_final_2 <- sf_final %>%
  select(Accommodates, Bathrooms, Bedrooms, Beds, Check.In, Check.Out, 
         Property.type, Room.type, Extra.people, Weekly.discount, 
         Monthly.discount, Cancellation, Response.time, ID, price, e, city)
write_csv(sf_final_2, path = "cleaned_sf.csv")

la_final_2 <- la_final %>%
  select(Accommodates, Bathrooms, Bedrooms, Beds, Check.In, Check.Out, 
         Property.type, Room.type, Extra.people, Weekly.discount, 
         Monthly.discount, Cancellation, Response.time, ID, price, e, city)
write_csv(la_final_2, path = "cleaned_la.csv")

ch_final_2 <- ch_final %>%
  select(Accommodates, Bathrooms, Bedrooms, Beds, Check.In, Check.Out, 
         Property.type, Room.type, Extra.people, Weekly.discount, 
         Monthly.discount, Cancellation, Response.time, ID, price, e, city)
write_csv(ch_final_2, path = "cleaned_ch.csv")

ny_final_2 <- ny_final %>%
  select(Accommodates, Bathrooms, Bedrooms, Beds, Check.In, Check.Out, 
         Property.type, Room.type, Extra.people, Weekly.discount, 
         Monthly.discount, Cancellation, Response.time, ID, price, e, city)
ny_final_2 <- ny_final_2[,-c(1,2)]
write_csv(ny_final_2, path = "cleaned_ny.csv")

four_cities <- rbind(sf_final_2,ny_final_2) %>%
  rbind(la_final_2) %>%
  rbind(ch_final_2)
  
write_csv(four_cities, path = "four_cities.csv")  
```


```{r}
# this chunk cleans the four_cities csv
four_cities <- read_csv("four_cities.csv")

#this code replaces all NAs with string 'unspecified' and taking out time specifications in Check.In column
four_cities[is.na(four_cities)] <- "unspecified"
four_cities = four_cities %>%
  mutate(Check.In = str_replace(Check.In, "^Anytime after ","")) %>%
  mutate(Check.In = str_replace(Check.In, " \\(next day\\)", "")) %>%
  mutate(Check.In = str_replace(Check.In, " \\(midnight\\)", "")) %>%
  mutate(Check.In = str_replace(Check.In, " \\(noon\\)", ""))

four_cities = four_cities %>%
  mutate(Check.Out = str_replace(Check.Out, " \\(midnight\\)", "")) %>%
  mutate(Check.Out = str_replace(Check.Out, " \\(noon\\)", ""))


#this code creates a new column, earliest.check.in
check_in_times_PM <- four_cities %>%
  filter(Check.In = str_detect(Check.In, "^[1]?[123456789]?PM")) %>%
  mutate(Earliest.Check.In = str_extract(Check.In, "^[123456789]?PM"))

check_in_times_AM <- four_cities %>%
filter(Check.In = str_detect(Check.In, "^[1]?[123456789]?AM")) %>%
  mutate(Earliest.Check.In = str_extract(Check.In, "^[1]?[123456789]?AM"))

check_in_flexible <- four_cities %>%
  filter(Check.In = str_detect(Check.In, "Flexible")) %>%
  mutate(Earliest.Check.In = "Flexible")

check_in_unspecified <- four_cities %>%
  filter(Check.In = str_detect(Check.In, "unspecified")) %>%
  mutate(Earliest.Check.In = "Unspecified")

four_cities <- check_in_times_AM %>%
  rbind(check_in_times_PM) %>%
  rbind(check_in_unspecified) %>%
  rbind(check_in_flexible)

#this code cleans the Bathroom column; take out "shared" or "private"
four_cities <- four_cities %>%
  mutate(Bathrooms = str_replace(Bathrooms, " \\(Private\\)", "")) %>%
  mutate(Bathrooms = str_replace(Bathrooms, " \\(Shared\\)", ""))

#this code cleans the Extra.people column
four_cities <- four_cities %>%
  mutate(Extra.people = str_replace(Extra.people," / night after", "")) %>%
  mutate(Extra.people = str_replace(Extra.people," [1]?[02345] guest[s]?", "")) 

#this code cleans the Weekly.discount and Monthly.discount columns
four_cities <- four_cities %>%
  mutate(Weekly.Discount = str_replace(Weekly.Discount,"%","")) %>%
  mutate(Monthly.Discount = str_replace(Monthly.Discount, "%", ""))

names(four_cities) <- c("Accomodates", "Bathroom(s)", "Bedroom(s)", "Bed(s)", 
                        "Check.In", "Check.Out", "Property.Type", "Room.Type",
                        "Cost.Per.Extra.Person", "Weekly.Discount(%)", "Monthly.Discount(%)",
                        "Cancellation.Policy", "Response.Time", "ID", "Price", "e", 
                        "City", "Earliest.Check.In")
write_csv(four_cities, path = "clean_four_cities.csv")
```

