---
title: "vis_2_a_plot"
author: "judy teng"
date: "August 3, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)

price_guest_df <- read_csv("updated_cleaned_four_cities.csv") %>%
  select(Accomodates, Price, City, Price.Per.Indv)

#y scale is price per night
 ggplot(price_guest_df, 
         aes(y = Price, 
             x = Accomodates, 
             color = City)) +
  geom_point(stat= "identity", 
             position = position_dodge()) +
  geom_smooth(method = "lm", formula = y~log(x), se = FALSE) +
  scale_y_log10(breaks = seq(0,1000,100)) +
  scale_x_continuous(breaks = seq(0,13,1)) +
  labs(y = "Daily Price Per Night (USD)", 
       x = "Accomodations Per Room (Persons)",
       title = "Airbnb: Daily Price Trend Based on Persons Per Room") +
    theme_economist()
 
 
 
 #Graph extremly hard to read...don't use. Perhaps try price per person instead of price per night since there does seem to be some trend happening.
 
 #Find another form of geom for better readability; line, boxplot, or violin?
 
 #Log scale or no log scale? Line of best fit seem to work better with log scale, but determining whether to use log scale would depend on which geom we use to improve the graph..
 
```

