---
title: "Untitled"
author: "judy teng"
date: "July 31, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)

discount <- read_csv("cleaned_four_cities.csv")

discount <- discount %>%
  select(`Weekly.Discount(%)`,`Monthly.Discount(%)`, Price, City) %>%
  mutate(`Weekly.Discount(%)` = str_replace(`Weekly.Discount(%)`,"unspecified", 0),
         `Monthly.Discount(%)` = str_replace(`Monthly.Discount(%)`, "unspecified",0))

no_discount <- discount %>%
  filter(`Monthly.Discount(%)` == 0) %>%
  mutate(Weekly.Price = Price,
         Monthly.Price = Price) %>%
  select(-`Monthly.Discount(%)`, -`Weekly.Discount(%)`)


have_discount <- discount %>%
  filter(`Monthly.Discount(%)` != 0) %>%
  mutate(Weekly.Price = (1- 0.01*as.numeric(`Weekly.Discount(%)`))*Price,
         Monthly.Price = (1- 0.01*as.numeric(`Monthly.Discount(%)`))*Price) %>%
  select(-`Monthly.Discount(%)`, -`Weekly.Discount(%)`)

discount_final <- rbind(no_discount, have_discount) %>%
  gather(key = time , value = price, Weekly.Price, Monthly.Price) %>%
  mutate(City = factor(City, 
                       levels = c("sf","la","ch","nyc"),
                       labels = c("San Francisco","Los Angeles","Chicago","New York City")))

colnames(discount_final)[1] <- "Daily.Price"

ggplot(discount_final, aes(x= Daily.Price, 
              y = price, 
              color = City)) +
  geom_point(alpha = 0.5, stroke = 0.5) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_grid(~time) +
  labs(x = "Original Price", 
       y = "Discounted Price") +
  scale_y_continuous(breaks = seq(0,1000,200)) +
  scale_x_continuous(breaks = seq(0,1000,200)) +
  geom_abline(intercept = 0, slope = 1)
```

