
```{r}
library(readr)
library(plyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggthemes)
```

```{r}
four_cities <- read.csv("updated_cleaned_four_cities.csv")
```


##CLEANING CHECKED IN

```{r}
#disregarding those observations with an unspecified/flexible check in or check out time
four_cities <- four_cities %>% 
  filter(!Check.In == "unspecified") %>% 
  filter(!Check.In == "Flexible") %>% 
  filter(!is.na(Check.In)) %>% 
  filter(!Check.Out == "unspecified")

#only concerned with earliest check in times; removing ranges
four_cities$Check.In <- str_replace_all(four_cities$Check.In, "[ ]-.*", "")
#cleaning the times
#filters only pm check in values, removes pm, converts into numeric value and adds 12
#to put time into a 0-24hr interval for graphing
no_twelves_in <- four_cities %>% 
  filter(!str_detect(Check.In, "12")) %>% 
  mutate(Check.In = ifelse(str_detect(Check.In, "AM"),
                            as.numeric(str_replace_all(Check.In, "AM", "")), #as.numeric coerces NAs
                            as.numeric(str_replace_all(Check.In, "PM", ""))+12))

#for cases of midnight and noontimes
cleaned_in_df <- four_cities %>% 
  filter(str_detect(Check.In, "12")) %>% 
  mutate(Check.In = ifelse(str_detect(Check.In, "AM"),
                            as.numeric(str_replace_all(Check.In, "12AM", "0")), #as.numeric coerces NAs
                            as.numeric(str_replace_all(Check.In, "PM", ""))))
  

cleaned_in_df <- full_join(no_twelves_in, cleaned_in_df)


```




##CLEANING CHECKED OUT

```{r}

no_twelves_out <- four_cities %>% 
  filter(!str_detect(Check.Out, "12")) %>% 
  mutate(Check.Out = ifelse(str_detect(Check.Out, "AM"),
                            as.numeric(str_replace_all(Check.Out, "AM", "")), #as.numeric coerces NAs
                            as.numeric(str_replace_all(Check.Out, "PM", ""))+12))

cleaned_out_df <- four_cities %>% 
  filter(str_detect(Check.Out, "12")) %>% 
  mutate(Check.Out = ifelse(str_detect(Check.Out, "AM"),
                            as.numeric(str_replace_all(Check.Out, "12AM", "0")),
                            as.numeric(str_replace_all(Check.Out, "PM", ""))))

cleaned_out_df <- full_join(no_twelves_out, cleaned_out_df)


```

##Joined Together
```{r}
cleaned_in_df <- cleaned_in_df %>% 
  select(-Check.Out)
cleaned_out_df <- cleaned_out_df %>% 
  select(-Check.In)
cleaned_df <- full_join(cleaned_in_df, cleaned_out_df)

#mutating a factorized four_cities price_range column
cleaned_df <- cleaned_df %>% 
  mutate(Price.Range = (Price)) %>% 
  mutate(Price.Range = ifelse(Price < 50, 
                              "0-49", Price)) %>% 
  mutate(Price.Range = ifelse(Price >= 50 & Price < 100, 
                              "50-99", as.character(Price.Range))) %>% 
  mutate(Price.Range = ifelse(Price >= 100 & Price < 150, 
                              "100-149", as.character(Price.Range))) %>% 
  mutate(Price.Range = ifelse(Price >= 150 & Price < 200, 
                              "150-199", as.character(Price.Range))) %>% 
  mutate(Price.Range = ifelse(Price >= 200,
                              "200+", as.character(Price.Range)))

cleaned_df$Price.Range <- ordered(cleaned_df$Price.Range, levels = c("0-49", "50-99", "100-149", "150-199", "200+"))
```


##Plots

```{r}
#check in time density plot

#justification for filling by price range - are cheaper price ranges more accomodating
#in terms of check in times

city_names <- c(
  `ch` = "Chicago",
  `la` = "Los Angeles",
  `ny` = "New York",
  `sf` = "San Francisco"
)

ggplot(cleaned_df) +
  geom_density(alpha = 0.6, aes(Check.In, fill = Price.Range)) +
  labs(x= "Time of Day",
       y = "Density",
       title = "Figure 5a: Density Plot of Airbnb Check In Times") +
  facet_wrap(~City) +
  scale_x_continuous(limits=c(6,24), 
                     breaks=seq(6,24,4)) +
  guides(color = "none") +
  theme_gdocs() +
  theme(text = element_text(size=17))


#check out time density plot
ggplot(cleaned_df) +
  geom_density(alpha = 0.6, aes(Check.Out, fill = Price.Range)) +
  labs(x = "Time of Day",
       y = "Density",
       title = "Figure 5b: Density Plot of Airbnb Check Out Times") +
  facet_wrap(~City) +
  scale_x_continuous(limits=c(6,24), 
                     breaks=seq(6,24,4)) +
  guides(color = "none") +
  theme_gdocs() +
  theme(text = element_text(size=17))

```


